"use client";

import { Download } from "lucide-react";
import { LineChart, Line, ResponsiveContainer } from "recharts";
import { useWorkspace } from "@/context/WorkspaceContext";
import { useMetrics } from "@/hooks/useMetrics";
import { useState } from "react";
import html2canvas from "html2canvas";

export default function RevenuePage() {
  const { businessType, businessProfile } = useWorkspace();
  const { metrics } = useMetrics(null); // Just using mock data here for display
  const [showPL, setShowPL] = useState(false);

  const handleDownloadPL = async () => {
    const el = document.getElementById("pl-card");
    if (!el) return;
    const canvas = await html2canvas(el, { scale: 2, backgroundColor: null });
    const link = document.createElement("a");
    link.download = `clario-pl-${new Date().toISOString().split("T")[0]}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  return (
    <div className="max-w-5xl mx-auto">
      {showPL && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white dark:bg-[#141414] rounded-2xl max-w-md w-full shadow-2xl overflow-hidden">
            <div id="pl-card" className="p-8 bg-white dark:bg-[#141414]">
              <h2 className="text-xl font-bold mb-6 text-center text-[#0A0A0A] dark:text-white">Monthly P&L Snapshot</h2>
              <div className="space-y-4">
                <div className="flex justify-between text-sm">
                  <span className="text-[#6B7280]">Gross Revenue</span>
                  <span className="font-semibold text-[#0A0A0A] dark:text-white">$12,450.00</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-[#6B7280]">Cost of Goods / Service</span>
                  <span className="font-semibold text-[#EF4444]">-$2,100.00</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-[#6B7280]">Operating Expenses</span>
                  <span className="font-semibold text-[#EF4444]">-$4,350.00</span>
                </div>
                <div className="pt-4 border-t border-[rgba(0,0,0,0.1)] dark:border-[rgba(255,255,255,0.1)] flex justify-between">
                  <span className="font-bold text-[#0A0A0A] dark:text-white">Net Profit</span>
                  <span className="font-bold text-[#22C55E]">$6,000.00</span>
                </div>
                <div className="flex justify-between text-xs mt-1">
                  <span className="text-[#6B7280]">Profit Margin</span>
                  <span className="font-semibold text-[#22C55E]">48.2%</span>
                </div>
              </div>
              <div className="mt-8 text-center text-[10px] text-[#9CA3AF]">Generated by Clario</div>
            </div>
            <div className="p-4 bg-[rgba(0,0,0,0.02)] dark:bg-[rgba(255,255,255,0.02)] flex gap-3 border-t border-[rgba(0,0,0,0.06)] dark:border-[rgba(255,255,255,0.06)]">
              <button onClick={() => setShowPL(false)} className="flex-1 h-10 rounded-xl border font-semibold text-sm">Cancel</button>
              <button onClick={handleDownloadPL} className="flex-1 h-10 rounded-xl bg-[#0A0A0A] dark:bg-white text-white dark:text-black font-semibold text-sm flex items-center justify-center gap-2">
                <Download size={14} /> Download PNG
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-semibold text-[#0A0A0A] dark:text-white">Revenue</h1>
        <button onClick={() => setShowPL(true)} className="h-9 px-4 rounded-xl border border-[rgba(0,0,0,0.1)] dark:border-[rgba(255,255,255,0.1)] hover:bg-[rgba(0,0,0,0.03)] dark:hover:bg-[rgba(255,255,255,0.03)] font-medium flex items-center gap-2 transition-colors text-sm">
          <Download size={16} /> Generate P&L Card
        </button>
      </div>

      <div className="glass-card p-6 mb-6">
        <div className="flex justify-between items-center mb-8">
          <div>
            <h3 className="text-sm font-semibold text-[#0A0A0A] dark:text-white mb-1">Revenue Growth</h3>
            <p className="text-3xl font-bold text-[#0A0A0A] dark:text-white">${(businessProfile?.mrr || 12450).toLocaleString()}</p>
          </div>
          <div className="flex gap-2">
            {["7D", "30D", "90D"].map((tab, i) => (
              <button key={tab} className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${i===1 ? "bg-[#0A0A0A] dark:bg-white text-white dark:text-black" : "bg-[rgba(0,0,0,0.04)] dark:bg-[rgba(255,255,255,0.04)] text-[#6B7280]"}`}>
                {tab}
              </button>
            ))}
          </div>
        </div>
        <div className="h-72 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={metrics}>
              <Line type="monotone" dataKey="mrr" stroke="#F97316" strokeWidth={2} dot={false} fill="rgba(249,115,22,0.06)" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="glass-card p-6">
          <h3 className="text-sm font-semibold text-[#0A0A0A] dark:text-white mb-4">Cash Runway</h3>
          <div className="flex items-end gap-2 mb-4">
            <span className="text-4xl font-bold text-[#0A0A0A] dark:text-white">14.2</span>
            <span className="text-[#9CA3AF] mb-1">months</span>
          </div>
          <div className="w-full h-2 bg-[rgba(0,0,0,0.06)] dark:bg-[rgba(255,255,255,0.06)] rounded-full overflow-hidden">
            <div className="h-full bg-[#22C55E]" style={{ width: "70%" }} />
          </div>
        </div>

        {businessType === "agency" ? (
          <div className="glass-card p-6">
            <h3 className="text-sm font-semibold text-[#0A0A0A] dark:text-white mb-4">Client Concentration</h3>
            <div className="flex items-end gap-2 mb-4">
              <span className="text-4xl font-bold text-[#F59E0B]">15%</span>
              <span className="text-[#9CA3AF] mb-1">top client</span>
            </div>
            <p className="text-[13px] text-[#6B7280]">Your largest client accounts for 15% of your total MRR. This is a moderate risk factor.</p>
          </div>
        ) : (
          <div className="glass-card p-6">
            <h3 className="text-sm font-semibold text-[#0A0A0A] dark:text-white mb-4">Average Order Value (AOV)</h3>
            <div className="flex items-end gap-2 mb-4">
              <span className="text-4xl font-bold text-[#22C55E]">$85</span>
              <span className="text-[#9CA3AF] mb-1">/ order</span>
            </div>
            <p className="text-[13px] text-[#6B7280]">AOV is up 4% this month, largely driven by the new cross-sell post-purchase flow.</p>
          </div>
        )}
      </div>

      <div className="mt-6 glass-card p-4 border-l-[2px] border-l-[rgba(249,115,22,0.4)] flex gap-3 items-start">
        <div className="w-2 h-2 rounded-full bg-[#6B7280] mt-1.5 shrink-0" />
        <div>
          <p className="text-sm font-semibold text-[#0A0A0A] dark:text-white mb-1">Axo Insight</p>
          <p className="text-[13px] text-[#6B7280]">Based on your current trajectory, you are on pace to hit your 90-day goal 12 days early. The primary constraint right now is fulfillment capacity, not revenue generation.</p>
        </div>
      </div>
    </div>
  );
}
